version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: 192.168.56.104
      DB_NAME: banque_app
      DB_USER: Cesario
      DB_PASS: "Timonlechat16&"

#volumes:
#  db_data:
