version: '3.8'

services:
  web:
    build: ./backend
    expose:
      - "80"  # On expose le port 80 pour que HAProxy puisse y accéder
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: 192.168.56.104
      DB_NAME: banque_app
      DB_USER: Cesario
      DB_PASS: "Timonlechat16&"

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - web
